### ISSUE TITLE
Doesn't work and gives out an error

### ISSUE THREAD

**Issue by F0rsX** [b31ngd3v/bomberthon#14]
Traceback (most recent call last):
  File "/home/user/bomberthon/bomberthon.py", line 61, in <module>
    smsbombinglinux()
  File "/home/user/bomberthon/smsprocess.py", line 160, in smsbombinglinux
    browser = webdriver.Firefox(executable_path=cr_dict , options=options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by b31ngd3v** [comment]
sorry this repo is not maintained anymore!

**Comment by Nocturnal-Compiler** [comment]
hey! just to check, have you installed firefox on your computer? because it will throw errors as such if you don't have it installed
