### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by highrider0602** [b31ngd3v/bomberthon#15]
Hey as the title suggests im getting a traceback error when running the program.  

here is the output when i chose the option for the whatsapp bomber

    |-> 4
Traceback (most recent call last):
  File "/opt/bomberthon/bomberthon.py", line 54, in <module>
    wpbombinglinux()
  File "/opt/bomberthon/wpprocess.py", line 110, in wpbombinglinux
    browser = webdriver.Firefox(executable_path=cr_dict , options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Below is the error for the sms bomber against my own phone number

    |-$ Enter Your Country Code (Without +) > 1
    |-$ Enter Target Number >  +1 7373098433
    |-$ How many times (1-200) ? > 200
Traceback (most recent call last):
  File "/opt/bomberthon/bomberthon.py", line 61, in <module>
    smsbombinglinux()
  File "/opt/bomberthon/smsprocess.py", line 160, in smsbombinglinux
    browser = webdriver.Firefox(executable_path=cr_dict , options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Here is thhe output for the instagram bomber

    |-> 1
    |-$ Word/Sentence that you want to send Multiple Times > hello  
    |-$ How many times ? > 200
    |-} Logging in...
Traceback (most recent call last):
  File "/opt/bomberthon/bomberthon.py", line 44, in <module>
    igbombinglinux()
  File "/opt/bomberthon/igprocess.py", line 196, in igbombinglinux
    browser = webdriver.Firefox(executable_path=cr_dict , options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by b31ngd3v** [comment]
this tool is not maintained anymore, sorry!
