### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by jigsaw678** [b31ngD3v/bomberthon#4]
```
Traceback (most recent call last):
  File "/home/odin/bomberthon/bomberthon.py", line 61, in <module>
    smsbombinglinux()
  File "/home/odin/bomberthon/smsprocess.py", line 116, in smsbombinglinux
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

```selenium is already installed

**Comment by SGC-GamerZ** [comment]
Pls solve! it
![image](https://user-images.githubusercontent.com/79748628/121865517-ae7a6500-cd1b-11eb-9657-af912a381268.png)

**Comment by Nocturnal-Compiler** [comment]
> Pls solve! it ![image](https://user-images.githubusercontent.com/79748628/121865517-ae7a6500-cd1b-11eb-9657-af912a381268.png)

if you are running on windows os, it's the most stable one so far, please use it normally in your powershell instead of windows subsystem
